//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immeubiliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Immeubiliers()
        {
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int id_immeubiliers { get; set; }
        public int nbr_chambre { get; set; }
        public string status { get; set; }
        public int id_categories { get; set; }
        public string description { get; set; }
        public string nom_proprietaire { get; set; }
        public string tel_proprietaire { get; set; }
        public float superficie { get; set; }
        public Nullable<int> id_villes { get; set; }
        public Nullable<int> id_quartiers { get; set; }
        public float tarif { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Quartiers Quartiers { get; set; }
        public virtual Villes Villes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservations> Reservations { get; set; }
    }
}
